// @ts-nocheck
// The 10 liminal environments. Each is a data-driven level config consumed by
// levelgen.js and builder.js. Pure data — Node-testable.

export const ENVIRONMENTS = [
  // 0. THE FOYER — tutorial / lobby. Doors everywhere. Warm, empty lobby.
  {
    id: 'foyer',
    name: 'THE FOYER',
    subtitle: 'Nobody is checking in. The doors only open one way.',
    grid: [40, 40],
    rooms: { min: 8, max: 11, minW: 4, maxW: 8, minH: 4, maxH: 8, gap: 2 },
    corridorWidth: 2,
    palette: {
      bg: 0x171310, fog: 0x1b1611, floor: 0x3a332a, floorAlt: 0x332c25, wall: 0xcfc4b2, wallAlt: 0xc4b9a6,
      trim: 0x8a7a63, accent: 0x5e4a2e, panel: 0xffe8bd,
    },
    fog: [7, 42],
    ambient: { color: 0xfff2d0, intensity: 0.22 },
    lightDensity: 0.85,
    lightColor: 0xffe6b0,
    lightIntensity: 0.8,
    props: { sofa: 1, plant: 1, counter: 1, pillar: 1, bench: 1, sign: 1, trash: 1 },
    propChance: 0.5,
    containers: ['bin', 'desk', 'box'],
    enemyPool: [{ id: 'host', w: 1 }],
    enemyChance: 0.35,
    loot: 'generic',
    ambience: { drone: 96, drone2: 122, droneGain: 0.05, noiseFilter: 900, noiseGain: 0.004 },
    events: ['whisper', 'flicker', 'phantomStep', 'doorSlam', 'coldSpot'],
    mechanics: ['doorHide'],
    darkness: 0,
    lore: [
      { id: 'foyer1', title: 'Front Desk Log, 3:11 AM', text: 'Guest 402 never checked out. We knocked. The door was open and the room was gone — just a white wall where the door should have been. Maintenance says the hallway is one door longer today.' },
      { id: 'foyer2', title: 'Bellhop Note', text: 'If you meet the tall one with no reflection, do NOT offer to carry its bag. Just walk. Keep walking until the lobby smells like dust again. That is how you know the elevator works.' },
      { id: 'foyer3', title: 'A Guestbook Entry', text: 'Checked in August 3rd. Room key still works. The elevator only goes down now, and the buttons are all labeled with my handwriting. I am checking out forever.' },
    ],
  },

  // 1. THE HALLWAY — endless grey-blue corridor. Flickering lights telegraph the Lingerer.
  {
    id: 'hallway',
    name: 'THE HALLWAY',
    subtitle: 'Every door leads to another hallway. This one is longer than it should be.',
    grid: [46, 46],
    rooms: { min: 10, max: 14, minW: 3, maxW: 6, minH: 3, maxH: 6, gap: 3 },
    corridorWidth: 2,
    palette: {
      bg: 0x0c0f12, fog: 0x101418, floor: 0x2a3036, floorAlt: 0x252a2f, wall: 0x9aa2a8, wallAlt: 0x8d959b,
      trim: 0x5b6268, accent: 0x2f4a55, panel: 0xdbe6ec,
    },
    fog: [8, 46],
    ambient: { color: 0xdbe6ff, intensity: 0.16 },
    lightDensity: 0.9,
    lightColor: 0xd7e8f0,
    lightIntensity: 0.9,
    props: { door: 1, lamp: 1, pillar: 0.6, shelf: 0.4, trash: 0.5 },
    propChance: 0.6,
    containers: ['locker', 'bin', 'desk'],
    enemyPool: [{ id: 'lingerer', w: 1 }],
    enemyChance: 0.55,
    loot: 'generic',
    ambience: { drone: 82, drone2: 110, droneGain: 0.06, noiseFilter: 700, noiseGain: 0.006 },
    events: ['flickerBurst', 'whisper', 'phantomStep', 'alarm', 'doorSlam'],
    mechanics: ['flickerTelegraph'],
    darkness: 0.15,
    lore: [
      { id: 'hall1', title: 'Maintenance Sticker', text: 'REPLACE BULB — this hallway does not exist on any floor plan. It is simply the space between floor 4 and floor 5. The Lingerer lives in the dark spaces between the lights. Keep the lights on.' },
      { id: 'hall2', title: 'Housekeeping Log', text: 'Room 555 has been cleaned 214 times this month. Nobody can find the door. It is behind the flickering light at the end of the north corridor, but the flickering light is always two doors further away.' },
    ],
  },

  // 2. THE BACKROOMS — yellow wallpaper, damp carpet, radio static.
  {
    id: 'backrooms',
    name: 'THE BACKROOMS',
    subtitle: 'The space behind. Humid, yellow, and impossibly consistent.',
    grid: [52, 52],
    rooms: { min: 12, max: 16, minW: 3, maxW: 7, minH: 3, maxH: 7, gap: 1 },
    corridorWidth: 3,
    palette: {
      bg: 0x241f12, fog: 0x2a2515, floor: 0x9c8f60, floorAlt: 0x8f8156, wall: 0xd6c46e,
      wallAlt: 0xc9b75f, trim: 0x6d6236, accent: 0x54481f, panel: 0xf0e2a0,
    },
    fog: [6, 40],
    ambient: { color: 0xfff3b0, intensity: 0.3 },
    lightDensity: 1.0,
    lightColor: 0xf2e09a,
    lightIntensity: 1.0,
    props: { rack: 1, crate: 1, pillar: 1, machine: 0.7, cable: 0.8 },
    propChance: 0.7,
    containers: ['box', 'bin', 'shelf', 'cabinet'],
    enemyPool: [{ id: 'tuner', w: 1 }],
    enemyChance: 0.6,
    loot: 'backrooms',
    ambience: { drone: 128, drone2: 133, droneGain: 0.08, noiseFilter: 600, noiseGain: 0.008, hum: true },
    events: ['staticBurst', 'flicker', 'whisper', 'phantomStep', 'alarm'],
    mechanics: ['staticRadio', 'soundAttract'],
    darkness: 0.1,
    lore: [
      { id: 'back1', title: 'Radio Transmission', text: '— if you can hear this, you are in the back area. Stop moving. The Tuner navigates by sound, and you are the loudest thing down here. Crouch. Breathe into your sleeve. It leaves when the static resolves into a single clear tone.' },
      { id: 'back2', title: 'Wall Graffiti', text: 'i walked for three days and the carpet changed at the wall. that was the only change. the hum got closer. i left my radio on as a decoy. i hope it worked.' },
      { id: 'back3', title: 'A Scrap of Paper', text: 'Do not drink the water. Do not trust the quiet rooms. The yellow is the only constant. Follow the static — the static always points at something new.' },
    ],
  },

  // 3. THE POOL — drained municipal pool. Water rises. Stay in the light.
  {
    id: 'pool',
    name: 'THE POOL',
    subtitle: 'The water level is not a suggestion.',
    grid: [48, 48],
    rooms: { min: 10, max: 14, minW: 4, maxW: 9, minH: 4, maxH: 9, gap: 2 },
    corridorWidth: 3,
    palette: {
      bg: 0x0a1412, fog: 0x0d1a17, floor: 0x2e5650, floorAlt: 0x27504a, wall: 0x8fb8b2,
      wallAlt: 0x83aca6, trim: 0x3a6a63, accent: 0x1a3a36, panel: 0xc8e6e0,
    },
    fog: [7, 44],
    ambient: { color: 0xc8fff0, intensity: 0.18 },
    lightDensity: 0.7,
    lightColor: 0xbfffe8,
    lightIntensity: 1.1,
    props: { pillar: 1, ladder: 0.6, tile: 1, bleacher: 0.5, poolEdge: 1 },
    propChance: 0.6,
    containers: ['locker', 'bin', 'cabinet', 'corpse'],
    enemyPool: [{ id: 'drown', w: 1 }],
    enemyChance: 0.55,
    loot: 'generic',
    ambience: { drone: 60, drone2: 74, droneGain: 0.06, noiseFilter: 400, noiseGain: 0.01, water: true },
    events: ['waterRise', 'flicker', 'whisper', 'coldSpot', 'drip'],
    mechanics: ['waterRise', 'lightSafe'],
    darkness: 0.2,
    lore: [
      { id: 'pool1', title: 'Lifeguard Log', text: '09:00 water drained for maintenance. 09:41 drain closed itself. 10:05 the pool filled to exactly one inch below the deck, no source. 10:09 a shape under the surface, walking on the tile. 10:10 the surface was glass again. Check the tiles, keep the lights on.' },
      { id: 'pool2', title: 'Chalkboard Message', text: 'SWIM TEST CANCELLED. The Drown teaches that lesson now. It comes up through the dark water. Stand on the light tiles and it stays in the deep.' },
    ],
  },

  // 4. THE OFFICE — cubicles, fluorescent hum, The Paper spreads.
  {
    id: 'office',
    name: 'THE OFFICE',
    subtitle: 'Open plan. Endless meeting rooms. The paper is growing.',
    grid: [50, 50],
    rooms: { min: 11, max: 15, minW: 4, maxW: 8, minH: 4, maxH: 8, gap: 2 },
    corridorWidth: 3,
    palette: {
      bg: 0x15161a, fog: 0x1a1c20, floor: 0x4a4e58, floorAlt: 0x434750, wall: 0xcdd2da,
      wallAlt: 0xc2c7d0, trim: 0x6b7078, accent: 0x3a5f7a, panel: 0xeef3fa,
    },
    fog: [8, 48],
    ambient: { color: 0xe8f0ff, intensity: 0.3 },
    lightDensity: 0.95,
    lightColor: 0xeef6ff,
    lightIntensity: 1.0,
    props: { cubicle: 1, desk: 1, chair: 1, computer: 0.7, plant: 0.5, shelf: 0.5, blinds: 1 },
    propChance: 0.85,
    containers: ['desk', 'shelf', 'bin', 'cabinet'],
    enemyPool: [{ id: 'paper', w: 1 }],
    enemyChance: 0.5,
    loot: 'office',
    ambience: { drone: 140, drone2: 141, droneGain: 0.05, noiseFilter: 1000, noiseGain: 0.004, hum: true },
    events: ['alarm', 'flickerBurst', 'paperRustle', 'phantomStep', 'staticBurst'],
    mechanics: ['paperGrowth', 'blindReveal'],
    darkness: 0.05,
    lore: [
      { id: 'off1', title: 'Memo: Subject — The Filing', text: 'Effective immediately, all physical documents will be filed in the new annex. The annex grows. We stopped measuring it last quarter. Do not touch the walls of paper. If you hear rustling, close the blinds and be still — it only moves in the open.' },
      { id: 'off2', title: 'Email Draft', text: 'Team, the copier is printing pages with no source file again. Also the pages are moving. I logged out. I do not intend to log back in. Do not print.' },
    ],
  },

  // 5. THE MALL — empty retail. Mannequins. Look away and they move.
  {
    id: 'mall',
    name: 'THE MALL',
    subtitle: 'After hours. Forever. The mannequins have opinions.',
    grid: [54, 54],
    rooms: { min: 12, max: 16, minW: 4, maxW: 10, minH: 4, maxH: 10, gap: 3 },
    corridorWidth: 4,
    palette: {
      bg: 0x191722, fog: 0x201d29, floor: 0x6a6476, floorAlt: 0x635d6e, wall: 0xe8e2ee,
      wallAlt: 0xdbd5e4, trim: 0x8a8496, accent: 0x7a4f9e, panel: 0xfff4e0,
    },
    fog: [10, 55],
    ambient: { color: 0xf2e8ff, intensity: 0.26 },
    lightDensity: 0.9,
    lightColor: 0xfff1d6,
    lightIntensity: 0.9,
    props: { kiosk: 1, mannequin: 1, bench: 0.7, plant: 0.8, pillar: 0.6, escalator: 0.5, sign: 0.8 },
    propChance: 0.8,
    containers: ['shelf', 'bin', 'desk', 'corpse'],
    enemyPool: [{ id: 'mannequin', w: 1 }],
    enemyChance: 0.7,
    loot: 'generic',
    ambience: { drone: 66, drone2: 96, droneGain: 0.05, noiseFilter: 550, noiseGain: 0.005 },
    events: ['mannequinShift', 'flicker', 'whisper', 'phantomStep', 'staticBurst'],
    mechanics: ['weepingAngel', 'escalator'],
    darkness: 0.1,
    lore: [
      { id: 'mall1', title: 'Security Note', text: 'They do not move when you look at them. Everyone thinks it is a trick. The trick is that they are fast when you look away, and the store exits lock behind you. Shop in the light. Never blink in the dressing rooms.' },
      { id: 'mall2', title: 'Lost Child Report', text: 'Mother reports child went into the toy store. Every mannequin in the toy store was assembled wrong this morning. The child has not been found. The mannequins have been reported to stand closer to the camera every hour.' },
    ],
  },

  // 6. THE HOSPITAL — mint green wards. The Nurse hears you breathe.
  {
    id: 'hospital',
    name: 'THE HOSPITAL',
    subtitle: 'Admission: eternal. The Nurse is on rounds.',
    grid: [50, 50],
    rooms: { min: 11, max: 15, minW: 4, maxW: 8, minH: 4, maxH: 8, gap: 2 },
    corridorWidth: 3,
    palette: {
      bg: 0x0f1614, fog: 0x141c19, floor: 0x9fbfb4, floorAlt: 0x93b4a9, wall: 0xbfe0d6,
      wallAlt: 0xb2d4ca, trim: 0x5f837a, accent: 0x8a2b3a, panel: 0xe6fff6,
    },
    fog: [8, 46],
    ambient: { color: 0xe0fff2, intensity: 0.24 },
    lightDensity: 0.9,
    lightColor: 0xe8fff4,
    lightIntensity: 1.0,
    props: { bed: 1, gurney: 0.5, cabinet: 1, monitor: 0.6, curtain: 0.7, sign: 0.5 },
    propChance: 0.8,
    containers: ['cabinet', 'locker', 'bin', 'corpse', 'desk'],
    enemyPool: [{ id: 'nurse', w: 1 }],
    enemyChance: 0.5,
    loot: 'hospital',
    ambience: { drone: 220, drone2: 224, droneGain: 0.04, noiseFilter: 1300, noiseGain: 0.005, hum: true },
    events: ['heartbeat', 'flicker', 'doorSlam', 'whisper', 'alarm'],
    mechanics: ['holdBreath', 'sedativeCloud'],
    darkness: 0.15,
    lore: [
      { id: 'hosp1', title: 'Nurse Station Note', text: 'ROUNDS: The Nurse does not respond to sight. She responds to breath. If you are still and you do not breathe — truly not breathe — she walks past you. People who hold their breath live. People who gasp do not.' },
      { id: 'hosp2', title: 'Patient Chart — 4B', text: 'Admitted: no record. Diagnosis: she is still here. Treatment: the sedative makes the eyes heavy. Do not fall asleep in 4B. The curtains in 4B close themselves.' },
      { id: 'hosp3', title: 'Scrubbed Message on the Wall', text: 'the pills in the cabinet are not medicine. they are the reason the ward never empties. take bandages, not pills.' },
    ],
  },

  // 7. THE SCHOOL — empty classrooms. Answer the phones. Hide in lockers.
  {
    id: 'school',
    name: 'THE SCHOOL',
    subtitle: 'The phones are ringing. Somebody has to answer.',
    grid: [50, 50],
    rooms: { min: 12, max: 16, minW: 4, maxW: 8, minH: 4, maxH: 8, gap: 2 },
    corridorWidth: 3,
    palette: {
      bg: 0x151310, fog: 0x1a1814, floor: 0x8a7f6a, floorAlt: 0x80755f, wall: 0xcfc3a8,
      wallAlt: 0xc4b89c, trim: 0x6d6248, accent: 0x6b4a2f, panel: 0xf4ecd2,
    },
    fog: [7, 44],
    ambient: { color: 0xfff0c8, intensity: 0.26 },
    lightDensity: 0.85,
    lightColor: 0xfff1c4,
    lightIntensity: 0.9,
    props: { desk: 1, chair: 1, locker: 1, whiteboard: 0.7, bookshelf: 0.6, phone: 1, flag: 0.4 },
    propChance: 0.85,
    containers: ['desk', 'locker', 'shelf', 'cabinet', 'bin'],
    enemyPool: [{ id: 'principal', w: 1 }],
    enemyChance: 0.55,
    loot: 'generic',
    ambience: { drone: 150, drone2: 152, droneGain: 0.04, noiseFilter: 800, noiseGain: 0.004, hum: true },
    events: ['phoneRing', 'flicker', 'bell', 'phantomStep', 'doorSlam'],
    mechanics: ['phoneRing', 'lockerHide'],
    darkness: 0.1,
    lore: [
      { id: 'school1', title: 'Office Note', text: 'When a phone rings, it is a test. You have until the third ring. Answer it — say nothing, just lift the receiver — and the Principal loses your trail. Ignore it and the Principal is suddenly where you are. There is no hallway long enough.' },
      { id: 'school2', title: 'Gym Bleacher Graffiti', text: 'the Principal hates the dark. hide in the lockers during the bell. it counts you in your seats. every seat is occupied by a student that isnt here anymore.' },
      { id: 'school3', title: 'Principal Letterhead', text: 'Dear Parents, we regret to inform you that your child has been retained indefinitely. The building requires a full classroom. Attendance is mandatory. The bell is the signal. Do not be late.' },
    ],
  },

  // 8. THE METRO — dark tunnels, rails, phantom trains.
  {
    id: 'metro',
    name: 'THE METRO',
    subtitle: 'Last train departed never. Mind the gap.',
    grid: [54, 54],
    rooms: { min: 10, max: 14, minW: 3, maxW: 6, minH: 3, maxH: 6, gap: 3 },
    corridorWidth: 3,
    palette: {
      bg: 0x0a0a0c, fog: 0x101014, floor: 0x23262b, floorAlt: 0x1e2126, wall: 0x5a5e66,
      wallAlt: 0x4f535b, trim: 0x2e3136, accent: 0x8a3b2f, panel: 0xffd9b0,
    },
    fog: [6, 40],
    ambient: { color: 0xffc9a0, intensity: 0.12 },
    lightDensity: 0.6,
    lightColor: 0xffd9b0,
    lightIntensity: 1.2,
    props: { rail: 1, bench: 0.6, pillar: 1, sign: 0.8, cable: 0.6, tunnelDoor: 0.7 },
    propChance: 0.6,
    containers: ['bin', 'locker', 'cabinet', 'corpse'],
    enemyPool: [{ id: 'conductor', w: 1 }],
    enemyChance: 0.6,
    loot: 'metro',
    ambience: { drone: 58, drone2: 70, droneGain: 0.07, noiseFilter: 300, noiseGain: 0.01 },
    events: ['trainWhistle', 'flickerBurst', 'phantomStep', 'staticBurst', 'coldSpot'],
    mechanics: ['phantomTrain', 'alcoveHide'],
    darkness: 0.35,
    lore: [
      { id: 'metro1', title: 'Station Notice', text: 'THE 2:00 AM TRAIN DOES NOT STOP HERE. It does not slow down. It does not have windows. If you hear the whistle, stand in an alcove and do not move. The Conductor counts passengers from the tunnel mouth.' },
      { id: 'metro2', title: 'Ticket Stub', text: 'One-way to the last station. Valid forever. No refunds. The Conductor can smell your ticket. If it asks for your fare, give it your flashlight. It collects light.' },
    ],
  },

  // 9. THE VOID — the final descent. The Architect.
  {
    id: 'void',
    name: 'THE VOID',
    subtitle: 'There was never a bottom. Only him.',
    grid: [44, 44],
    rooms: { min: 6, max: 8, minW: 8, maxW: 12, minH: 8, maxH: 12, gap: 4 },
    corridorWidth: 4,
    palette: {
      bg: 0x05050a, fog: 0x08080f, floor: 0x1a1a2a, floorAlt: 0x151524, wall: 0x2e2e4a,
      wallAlt: 0x282842, trim: 0x101020, accent: 0x7a1f3d, panel: 0x3a1440,
    },
    fog: [6, 38],
    ambient: { color: 0x5a2a6a, intensity: 0.08 },
    lightDensity: 0.35,
    lightColor: 0x6a2a7a,
    lightIntensity: 0.7,
    props: { pillar: 1, monolith: 0.6, shard: 0.5 },
    propChance: 0.5,
    containers: ['bin', 'cabinet', 'corpse'],
    enemyPool: [{ id: 'shade', w: 1 }],
    enemyChance: 0.3,
    loot: 'void',
    ambience: { drone: 42, drone2: 46, droneGain: 0.09, noiseFilter: 240, noiseGain: 0.008 },
    events: ['realityGlitch', 'whisper', 'staticBurst', 'coldSpot'],
    mechanics: ['bossArena'],
    darkness: 0.5,
    lore: [
      { id: 'void1', title: 'Final Message, Scratched in Stone', text: 'He built the rooms. Every hallway, every pool, every waiting area — rooms to keep us inside while he watched. There is no exit at the bottom. There is only him. Fight, or the liminal becomes permanent.' },
      { id: 'void2', title: 'A Name, Written and Erased', text: 'the architect keeps the doors because doors are his. he cannot build a window. when he glitches, the walls are honest for half a second — that is the only time to hurt him.' },
    ],
  },
]

export const ENV_INDEX = {}
for (let i = 0; i < ENVIRONMENTS.length; i++) ENV_INDEX[ENVIRONMENTS[i].id] = i

export function getEnv(floorIndex) {
  return ENVIRONMENTS[Math.min(Math.max(0, floorIndex), ENVIRONMENTS.length - 1)]
}

export const FLOOR_COUNT = ENVIRONMENTS.length
